# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json (if exists) for caching dependencies
COPY package.json ./
COPY pnpm-lock.yaml ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . ./

# Build the TypeScript code
RUN npm run build

# Expose any port if required by the server (not specified in README, so not exposing port)

# Start the server
CMD ["node", "build/horoscope.js"]
