# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the app
COPY . .

# Build the app
RUN npm run build

# Ensure the built file is executable
RUN chmod +x build/index.js

# Expose stdio ports if needed, but stdio servers generally don't need ports

# Run the MCP server
CMD ["node", "build/index.js"]
